; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File

[platform_common]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
lib_deps = 
    blynk
    rfetick/MPU6050_light@^1.1.0

[env:transmitter]
extends = platform_common
build_src_filter = +<transmitter.cpp> -<receiver.cpp> -<mac.cpp> -<control-app.cpp>
upload_port = COM5
monitor_port = COM5

[env:receiver]
extends = platform_common
build_src_filter = +<receiver.cpp> -<transmitter.cpp> -<mac.cpp> -<control-app.cpp>
upload_port = COM6
monitor_port = COM6